name: deploy-base-8
on:
  push:
    paths:
      - 'php/base/**'
      - 'config/php/fpm-pool.conf'
      - 'config/php/opcache.ini'
      - 'config/nginx/**'
      - 'config/supervisord.conf'
      - '.github/workflows/build-base-8.yml'
    branches:
      - 'develop'
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-latest:
    name: build images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        composer: [2]
        php: ["8.0", "8.1"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extraer metadata (not tags, labels) para Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: build and push to docker with PHP ${{ matrix.php }} and Composer ${{ matrix.composer }}
        uses: docker/build-push-action@v4
        with:
          file: ./php/8/Dockerfile.base
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.php }}-c${{ matrix.composer }}-base
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          build-args: |
            COMPOSER_VERSION=${{ matrix.composer }}
            PHP_VERSION=${{ matrix.php }}
