name: deploy
on:
  push:
    branches:
      - 'develop'
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        id: builder1
      - uses: docker/setup-buildx-action@v1
        id: builder2
      - name: Builder 1 name
        run: echo ${{ steps.builder1.outputs.name }}
      - name: Builder 2 name
        run: echo ${{ steps.builder2.outputs.name }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: build and push to docker with composer 1
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder1.outputs.name }}
          repository: ymiranda/php
          tag_with_ref: true
          tag_with_sha: true
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
          push: true
          tags: "docker.io/ymiranda/php:7.4-nginx-composer1-latest"
          context: .
          file: ./php/base/Dockerfile
          platforms: linux/amd64
          build-args: |
            COMPOSER_VERSION=1
            PHP_VERSION=7.4
      - name: build and push to docker with composer 2
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder2.outputs.name }}
          repository: ymiranda/php
          tag_with_ref: true
          tag_with_sha: true
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
          push: true
          tags: "docker.io/ymiranda/php:7.4-nginx-composer2-latest"
          context: .
          file: ./php/base/Dockerfile
          platforms: linux/amd64
          build-args: |
            COMPOSER_VERSION=2
            PHP_VERSION=7.4